//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaEscolarApi.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class CatalogoTipoCuenta
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CatalogoTipoCuenta()
        {
            this.FormaPago = new HashSet<FormaPago>();
        }
    
        public int Id_TipoCuenta { get; set; }
        public string TCue_Nombre { get; set; }
        public bool TCue_Estatus { get; set; }
        public System.DateTime TCue_FechaAlta { get; set; }
        public System.DateTime TCue_FechaModificacion { get; set; }
        public System.DateTime TCue_FechaBaja { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FormaPago> FormaPago { get; set; }
    }
}
