//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaEscolarApi.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class CatalogoEstados
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CatalogoEstados()
        {
            this.DireccionesUsuarios = new HashSet<DireccionesUsuarios>();
            this.Institucion = new HashSet<Institucion>();
        }
    
        public int Id_Estado { get; set; }
        public string Est_Nombre { get; set; }
        public bool Est_Estatus { get; set; }
        public System.DateTime Est_FechaAlta { get; set; }
        public System.DateTime Est_FechaModificacion { get; set; }
        public System.DateTime Est_FechaBaja { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DireccionesUsuarios> DireccionesUsuarios { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Institucion> Institucion { get; set; }
    }
}
