//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaEscolarApi.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class CatalogoTipoUsuario
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CatalogoTipoUsuario()
        {
            this.Usuarios = new HashSet<Usuarios>();
        }
    
        public int Id_TipoUsuario { get; set; }
        public string TUsu_Nombre { get; set; }
        public int TUsu_Clase { get; set; }
        public bool TUsu_Estatus { get; set; }
        public System.DateTime TUsu_FechaAlta { get; set; }
        public System.DateTime TUsu_FechaModificacion { get; set; }
        public System.DateTime TUsu_FechaBaja { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Usuarios> Usuarios { get; set; }
    }
}
