//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaEscolarApi.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class DireccionesUsuarios
    {
        public int Id_Direccion { get; set; }
        public int Dir_Id_Usuario { get; set; }
        public string Dir_Calle { get; set; }
        public string Dir_NumeroInt { get; set; }
        public string Dir_NumeroExt { get; set; }
        public string Dir_Colonia { get; set; }
        public string Dir_Delegacion { get; set; }
        public string Dir_Municipio { get; set; }
        public int Dir_Id_Estado { get; set; }
        public int Dir_CodigoPostal { get; set; }
        public bool Dir_Estatus { get; set; }
        public System.DateTime Dir_FechaAlta { get; set; }
        public System.DateTime Dir_FechaModificacion { get; set; }
        public System.DateTime Dir_FechaBaja { get; set; }
    
        public virtual CatalogoEstados CatalogoEstados { get; set; }
        public virtual Usuarios Usuarios { get; set; }
    }
}
