//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaEscolarApi.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Institucion
    {
        public int Id_Institucion { get; set; }
        public int Ins_Id_Usuario { get; set; }
        public string Ins_Nombre { get; set; }
        public string Ins_Clave { get; set; }
        public string Ins_Direccion { get; set; }
        public int Ins_CodigoPostal { get; set; }
        public int Ins_Id_Estado { get; set; }
        public string Ins_UrlLogo { get; set; }
        public bool Ins_Estatus { get; set; }
        public System.DateTime Ins_FechaAlta { get; set; }
        public System.DateTime Ins_FechaModificacion { get; set; }
        public System.DateTime Ins_FechaBaja { get; set; }
    
        public virtual CatalogoEstados CatalogoEstados { get; set; }
        public virtual Usuarios Usuarios { get; set; }
    }
}
