//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaEscolarApi.DB
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DB_A18E01_DBEscolarEntities : DbContext
    {
        public DB_A18E01_DBEscolarEntities()
            : base("name=DB_A18E01_DBEscolarEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CatalogoBancos> CatalogoBancos { get; set; }
        public virtual DbSet<CatalogoEstados> CatalogoEstados { get; set; }
        public virtual DbSet<CatalogoTipoCuenta> CatalogoTipoCuenta { get; set; }
        public virtual DbSet<CatalogoTipoUsuario> CatalogoTipoUsuario { get; set; }
        public virtual DbSet<DireccionesUsuarios> DireccionesUsuarios { get; set; }
        public virtual DbSet<EstadoCuenta> EstadoCuenta { get; set; }
        public virtual DbSet<FormaPago> FormaPago { get; set; }
        public virtual DbSet<Institucion> Institucion { get; set; }
        public virtual DbSet<PreguntaSecreta> PreguntaSecreta { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Usuarios> Usuarios { get; set; }
    }
}
