//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaEscolarApi.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class PreguntaSecreta
    {
        public int Id_Pregunta { get; set; }
        public int Pre_Id_Usuario { get; set; }
        public string Pre_Cuestion { get; set; }
        public string Pre_Respuesta { get; set; }
        public bool Pre_Estatus { get; set; }
        public System.DateTime Pre_FechaAlta { get; set; }
        public System.DateTime Pre_FechaModificacion { get; set; }
        public System.DateTime Pre_FechaBaja { get; set; }
    
        public virtual Usuarios Usuarios { get; set; }
    }
}
