//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaEscolarApi.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuarios
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Usuarios()
        {
            this.DireccionesUsuarios = new HashSet<DireccionesUsuarios>();
            this.EstadoCuenta = new HashSet<EstadoCuenta>();
            this.FormaPago = new HashSet<FormaPago>();
            this.Institucion = new HashSet<Institucion>();
            this.PreguntaSecreta = new HashSet<PreguntaSecreta>();
        }
    
        public int Id_Usuario { get; set; }
        public string Usu_ClaveUnica { get; set; }
        public string Usu_Nombre { get; set; }
        public string Usu_Curp { get; set; }
        public string Usu_Rfc { get; set; }
        public string Usu_ClaveDocente { get; set; }
        public string Usu_Turno { get; set; }
        public string Usu_CorreoElectronico { get; set; }
        public string Usu_Usuario { get; set; }
        public string Usu_Clave { get; set; }
        public string Usu_ConfirmaClave { get; set; }
        public int Usu_Id_TipoUsuario { get; set; }
        public bool Usu_Estatus { get; set; }
        public System.DateTime Usu_FechaAlta { get; set; }
        public System.DateTime Usu_FechaModificacion { get; set; }
        public System.DateTime Usu_FechaBaja { get; set; }
    
        public virtual CatalogoTipoUsuario CatalogoTipoUsuario { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DireccionesUsuarios> DireccionesUsuarios { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EstadoCuenta> EstadoCuenta { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FormaPago> FormaPago { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Institucion> Institucion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PreguntaSecreta> PreguntaSecreta { get; set; }
    }
}
